import { Order, OrderItem, ShippingAddress } from "@/types/orders";
import { saveOrders } from "@/lib/orderStorage";

/**
 * Seed order data for demo purposes
 * Call this function to populate orders for existing Smart Page sites
 */
export const seedOrderData = () => {
  // Check if orders already exist
  const existingOrders = localStorage.getItem("smart-page-orders-demo_store");
  if (existingOrders) {
    console.log("Orders already seeded");
    return;
  }

  console.log("Seeding order data...");

  // Demo store orders (assuming there's a demo e-commerce store site)
  const storeOrders: Order[] = [
    {
      id: "ord_001",
      websiteId: "demo_store",
      orderNumber: "ORD-2026-0001",
      customerName: "Priya Sharma",
      customerEmail: "priya.sharma@email.com",
      customerPhone: "+91 98765 43210",
      items: [
        {
          id: "item_001",
          productId: "prod_tshirt_001",
          productName: "Premium Cotton T-Shirt",
          productImage: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
          variantId: "var_001",
          variantName: "Blue, L",
          quantity: 2,
          price: 799,
          subtotal: 1598,
        },
        {
          id: "item_002",
          productId: "prod_jeans_001",
          productName: "Slim Fit Denim Jeans",
          quantity: 1,
          price: 2499,
          subtotal: 2499,
        },
      ],
      subtotal: 4097,
      shippingCost: 100,
      tax: 246,
      discount: 200,
      total: 4243,
      currency: "INR",
      status: "delivered",
      paymentStatus: "paid",
      paymentId: "pay_abc123xyz",
      shippingAddress: {
        fullName: "Priya Sharma",
        phone: "+91 98765 43210",
        addressLine1: "123, MG Road",
        addressLine2: "Near Central Mall",
        city: "Bengaluru",
        state: "Karnataka",
        pincode: "560001",
        country: "India",
      },
      trackingNumber: "DTDC1234567890",
      courierPartner: "DTDC",
      createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      paidAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      shippedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      deliveredAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "ord_002",
      websiteId: "demo_store",
      orderNumber: "ORD-2026-0002",
      customerName: "Rahul Verma",
      customerEmail: "rahul.v@gmail.com",
      customerPhone: "+91 87654 32109",
      items: [
        {
          id: "item_003",
          productId: "prod_sneakers_001",
          productName: "Sports Running Shoes",
          productImage: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
          variantId: "var_003",
          variantName: "White, 9",
          quantity: 1,
          price: 3999,
          subtotal: 3999,
        },
      ],
      subtotal: 3999,
      shippingCost: 0, // Free shipping
      tax: 240,
      discount: 400,
      total: 3839,
      currency: "INR",
      status: "shipped",
      paymentStatus: "paid",
      paymentId: "pay_def456ghi",
      shippingAddress: {
        fullName: "Rahul Verma",
        phone: "+91 87654 32109",
        addressLine1: "45/B, Sector 62",
        city: "Noida",
        state: "Uttar Pradesh",
        pincode: "201309",
        country: "India",
        landmark: "Near Metro Station",
      },
      trackingNumber: "BLUEDART9876543210",
      courierPartner: "Blue Dart",
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      paidAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      shippedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "ord_003",
      websiteId: "demo_store",
      orderNumber: "ORD-2026-0003",
      customerName: "Anjali Patel",
      customerEmail: "anjali.patel@email.com",
      customerPhone: "+91 76543 21098",
      items: [
        {
          id: "item_004",
          productId: "prod_dress_001",
          productName: "Floral Summer Dress",
          productImage: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400",
          variantId: "var_004",
          variantName: "Pink, M",
          quantity: 1,
          price: 1599,
          subtotal: 1599,
        },
        {
          id: "item_005",
          productId: "prod_bag_001",
          productName: "Leather Handbag",
          quantity: 1,
          price: 2999,
          subtotal: 2999,
        },
      ],
      subtotal: 4598,
      shippingCost: 100,
      tax: 276,
      discount: 0,
      total: 4974,
      currency: "INR",
      status: "processing",
      paymentStatus: "paid",
      paymentId: "pay_ghi789jkl",
      shippingAddress: {
        fullName: "Anjali Patel",
        phone: "+91 76543 21098",
        addressLine1: "78, Ring Road",
        addressLine2: "Satellite Area",
        city: "Ahmedabad",
        state: "Gujarat",
        pincode: "380015",
        country: "India",
      },
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      paidAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "ord_004",
      websiteId: "demo_store",
      orderNumber: "ORD-2026-0004",
      customerName: "Vikram Singh",
      customerEmail: "vikram.singh@email.com",
      customerPhone: "+91 65432 10987",
      items: [
        {
          id: "item_006",
          productId: "prod_watch_001",
          productName: "Smart Fitness Watch",
          productImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
          quantity: 1,
          price: 8999,
          subtotal: 8999,
        },
      ],
      subtotal: 8999,
      shippingCost: 0,
      tax: 540,
      discount: 900,
      total: 8639,
      currency: "INR",
      status: "confirmed",
      paymentStatus: "paid",
      paymentId: "pay_jkl012mno",
      shippingAddress: {
        fullName: "Vikram Singh",
        phone: "+91 65432 10987",
        addressLine1: "12, Connaught Place",
        city: "New Delhi",
        state: "Delhi",
        pincode: "110001",
        country: "India",
        landmark: "Near Metro Station",
      },
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      paidAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "ord_005",
      websiteId: "demo_store",
      orderNumber: "ORD-2026-0005",
      customerName: "Meera Reddy",
      customerEmail: "meera.reddy@gmail.com",
      customerPhone: "+91 54321 09876",
      items: [
        {
          id: "item_007",
          productId: "prod_kurta_001",
          productName: "Designer Kurta Set",
          productImage: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400",
          variantId: "var_005",
          variantName: "Navy Blue, L",
          quantity: 2,
          price: 1999,
          subtotal: 3998,
        },
      ],
      subtotal: 3998,
      shippingCost: 100,
      tax: 240,
      discount: 200,
      total: 4138,
      currency: "INR",
      status: "pending",
      paymentStatus: "paid",
      paymentId: "pay_mno345pqr",
      shippingAddress: {
        fullName: "Meera Reddy",
        phone: "+91 54321 09876",
        addressLine1: "56, Jubilee Hills",
        city: "Hyderabad",
        state: "Telangana",
        pincode: "500033",
        country: "India",
      },
      notes: "Please deliver in the evening after 6 PM",
      createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      paidAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "ord_006",
      websiteId: "demo_store",
      orderNumber: "ORD-2026-0006",
      customerName: "Amit Kumar",
      customerEmail: "amit.kumar@email.com",
      items: [
        {
          id: "item_008",
          productId: "prod_wallet_001",
          productName: "Genuine Leather Wallet",
          quantity: 1,
          price: 1299,
          subtotal: 1299,
        },
      ],
      subtotal: 1299,
      shippingCost: 50,
      tax: 78,
      discount: 0,
      total: 1427,
      currency: "INR",
      status: "cancelled",
      paymentStatus: "refunded",
      paymentId: "pay_pqr678stu",
      internalNotes: "Customer requested cancellation due to wrong size ordered",
      createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      paidAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "ord_007",
      websiteId: "demo_store",
      orderNumber: "ORD-2026-0007",
      customerName: "Sneha Gupta",
      customerEmail: "sneha.g@email.com",
      customerPhone: "+91 43210 98765",
      items: [
        {
          id: "item_009",
          productId: "prod_earrings_001",
          productName: "Silver Hoop Earrings",
          productImage: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400",
          quantity: 1,
          price: 899,
          subtotal: 899,
        },
        {
          id: "item_010",
          productId: "prod_necklace_001",
          productName: "Pearl Necklace",
          quantity: 1,
          price: 2499,
          subtotal: 2499,
        },
        {
          id: "item_011",
          productId: "prod_bracelet_001",
          productName: "Gold Plated Bracelet",
          quantity: 1,
          price: 1599,
          subtotal: 1599,
        },
      ],
      subtotal: 4997,
      shippingCost: 0,
      tax: 300,
      discount: 500,
      total: 4797,
      currency: "INR",
      status: "delivered",
      paymentStatus: "paid",
      paymentId: "pay_stu901vwx",
      shippingAddress: {
        fullName: "Sneha Gupta",
        phone: "+91 43210 98765",
        addressLine1: "34, Park Street",
        city: "Kolkata",
        state: "West Bengal",
        pincode: "700016",
        country: "India",
      },
      trackingNumber: "EKART5678901234",
      courierPartner: "Ekart",
      createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      paidAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      shippedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
      deliveredAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "ord_008",
      websiteId: "demo_store",
      orderNumber: "ORD-2026-0008",
      customerName: "Karan Malhotra",
      customerEmail: "karan.m@gmail.com",
      items: [
        {
          id: "item_012",
          productId: "prod_backpack_001",
          productName: "Travel Laptop Backpack",
          productImage: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
          quantity: 1,
          price: 2999,
          subtotal: 2999,
        },
      ],
      subtotal: 2999,
      shippingCost: 100,
      tax: 180,
      discount: 300,
      total: 2979,
      currency: "INR",
      status: "pending",
      paymentStatus: "pending",
      createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      internalNotes: "Waiting for payment confirmation",
    },
  ];

  // Save orders to localStorage
  saveOrders("demo_store", storeOrders);

  console.log(`Seeded ${storeOrders.length} orders for demo_store`);
};
